# Generated by Django 3.1.2 on 2022-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('Context', models.CharField(default='', max_length=10)),
                ('Details', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
