# Generated by Django 3.1.2 on 2022-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swatiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='Context',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='Details',
            field=models.CharField(default='', max_length=100),
        ),
    ]
